"""empty message

Revision ID: ce1fb599aa3d
Revises: 4c652ac92255
Create Date: 2022-11-06 19:19:20.721160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1fb599aa3d'
down_revision = '4c652ac92255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_categories',
    sa.Column('businesstable', sa.Integer(), nullable=True),
    sa.Column('categories', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['businesstable'], ['businesstable.id'], ),
    sa.ForeignKeyConstraint(['categories'], ['categories.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
